# Site settings
title: "李明科的简历"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "李明科"
resume_title:                   "新加坡国立大学 · 商业分析硕士"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "e0709106@u.nus.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "176-9567-2048"
resume_contact_address:         "#08-42 MDIS Residences, 503 Stirling Road, SG"

resume_header_contact_info:     "503 Stirling Rd SG, • 176-9567-2048 • e0709106@u.nus.edu"
display_header_contact_info:    "True"

resume_header_intro: "<p>Amigo! 您好，我是李明科，新加坡国立大学商业分析硕士在读，将于9月毕业，正在寻找数据科学相关工作岗位。这是我在课余时间学习制作的个人简历，介绍了大部分的学习和实践经历，将有助于您更好地了解我。当然，更多细节可以通过下方按钮邮件沟通，谢谢~</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/MinkoLee1999"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mingke-li-691a89201/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
